---
# tasks file for jitsi
- name: include assert.yml
  include_tasks: assert.yml

- name: install repository key
  apt_key:
    url: "https://download.jitsi.org/jitsi-key.gpg.key"
    validate_certs: no
    state: present
  register: jitsi_install_repository_key
  until: jitsi_install_repository_key is succeeded
  retries: 3

- name: add repository
  apt_repository:
    repo: "deb https://download.jitsi.org {{ jitsi_release }}/"
    filename: jitsi-{{ jitsi_release }}
    state: present
  register: jitsi_add_repository
  until: jitsi_add_repository is succeeded
  retries: 3

- name: set installer options
  debconf:
    name: "{{ item.name }}"
    question: "{{ item.question }}"
    value: "{{ item.value }}"
    vtype: "{{ item.type }}"
  loop: "{{ jitsi_settings }}"
  loop_control:
    label: "{{ item.question }}"

- name: install jitsi-meet
  package:
    name: jitsi-meet
    state: present
  register: jisti_install_jitsi_meet
  until: jisti_install_jitsi_meet is succeeded
  retries: 3
